MyMangaLibrary/Models/Manga.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MyMangaLibrary.Models
{
    public class Manga
    {
        public int ID { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        [Range(0, 10.00, ErrorMessage = "Rating cannot be more than 10!")]
        public decimal Rating { get; set; }
        [Required]
        [StringLength(255, ErrorMessage = "Name is too long!")]
        public string Name { get; set; } = null;
        [Range(0, int.MaxValue, ErrorMessage = "Chapter count cannot be less than 0!")]
        public int ChapterCount { get; set; }
        public string Summary { get; set; }

        [ForeignKey("MangakaID")]
        public int MangakaID { get; set; }
        public Mangaka Mangaka { get; set; }
    }
}

MyMangaLibrary/Controllers/MangakasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyMangaLibrary.Data;
using MyMangaLibrary.Models;

namespace MyMangaLibrary.Controllers
{
    public class MangakasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MangakasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Mangakas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Mangaka.ToListAsync());
        }
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            return View("Index", await _context.Mangaka.Where(m => m.Name.Contains(SearchPhrase)).ToListAsync());
        }
        // GET: Mangakas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mangaka = await _context.Mangaka
                .FirstOrDefaultAsync(m => m.ID == id);
            if (mangaka == null)
            {
                return NotFound();
            }

            return View(mangaka);
        }

        // GET: Mangakas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Mangakas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Age,Description")] Mangaka mangaka)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mangaka);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mangaka);
        }

        // GET: Mangakas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mangaka = await _context.Mangaka.FindAsync(id);
            if (mangaka == null)
            {
                return NotFound();
            }
            return View(mangaka);
        }

        // POST: Mangakas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Age,Description")] Mangaka mangaka)
        {
            if (id != mangaka.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mangaka);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MangakaExists(mangaka.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mangaka);
        }

        // GET: Mangakas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mangaka = await _context.Mangaka
                .FirstOrDefaultAsync(m => m.ID == id);
            if (mangaka == null)
            {
                return NotFound();
            }

            return View(mangaka);
        }

        // POST: Mangakas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mangaka = await _context.Mangaka.FindAsync(id);
            _context.Mangaka.Remove(mangaka);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MangakaExists(int id)
        {
            return _context.Mangaka.Any(e => e.ID == id);
        }
    }
}

MyMangaLibrary/Controllers/MangasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyMangaLibrary.Data;
using MyMangaLibrary.Models;

namespace MyMangaLibrary.Controllers
{
    public class MangasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MangasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Mangas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Manga.ToListAsync());
        }
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            return View("Index", await _context.Manga.Where( m => m.Name.Contains(SearchPhrase)).ToListAsync());
        }
        // GET: Mangas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Manga
                .FirstOrDefaultAsync(m => m.ID == id);
            if (manga == null)
            {
                return NotFound();
            }

            return View(manga);
        }

        // GET: Mangas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Mangas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Rating,Name,ChapterCount")] Manga manga)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manga);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(manga);
        }

        // GET: Mangas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Manga.FindAsync(id);
            if (manga == null)
            {
                return NotFound();
            }
            return View(manga);
        }

        [HttpPost]
        public ActionResult DecreaseChapter(int id) {
            if (id == null) {
                return NotFound();
            }
            var manga =  _context.Manga.Where(m => m.ID == id).FirstOrDefault();
            if (manga == null) {
                return NotFound();
            }

            manga.ChapterCount--;
            _context.Update(manga);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult IncreaseChapter(int id) {
            if (id == null) {
                return NotFound();
            }
            var manga =  _context.Manga.Where(m => m.ID == id).FirstOrDefault();
            if (manga == null) {
                return NotFound();
            }

            manga.ChapterCount++;
            _context.Update(manga);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        // POST: Mangas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Rating,Name,ChapterCount,Summary")] Manga manga)
        {
            if (id != manga.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(manga);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MangaExists(manga.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manga);
        }

        // GET: Mangas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Manga
                .FirstOrDefaultAsync(m => m.ID == id);
            if (manga == null)
            {
                return NotFound();
            }

            return View(manga);
        }

        // POST: Mangas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var manga = await _context.Manga.FindAsync(id);
            _context.Manga.Remove(manga);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MangaExists(int id)
        {
            return _context.Manga.Any(e => e.ID == id);
        }
    }
}

MyMangaLibrary/Views/Mangas/Create.cshtml
@model MyMangaLibrary.Models.Manga

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Manga</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChapterCount" class="control-label">Chapter Count</label>
                <input asp-for="ChapterCount" class="form-control" />
                <span asp-validation-for="ChapterCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MangakaID" class="control-label">Mangaka</label>
                <select asp-for="MangakaID" class ="form-control" asp-items="ViewBag.MangakaID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Summary" class="control-label"></label>
                <input asp-for="Summary" class="form-control" />
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-dark btn-sm" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyMangaLibrary/Views/Mangas/Delete.cshtml
@model MyMangaLibrary.Models.Manga

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>
        @Html.DisplayFor(model => model.Name)
    </h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChapterCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChapterCount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger btn-sm" />
        <a class="btn btn-dark btn-sm" asp-action="Index">Back to List</a>
    </form>
</div>

MyMangaLibrary/Views/Mangas/Details.cshtml
@model MyMangaLibrary.Models.Manga

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>
        @Html.DisplayFor(model => model.Name)
    </h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Chapter Count
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ChapterCount)
        </dd>
        <dt class = "col-sm-2">
            Mangaka
        </dt>
        <dd class = "col-sm-10">
            @Html.ActionLink(@Model.Mangaka.Name, "Details", "Mangakas", new { id = @Model.MangakaID})
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Summary)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Summary)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@Model.ID">Edit</a>
    <a class="btn btn-dark btn-sm"asp-action="Index">Back to List</a>
</div>

MyMangaLibrary/Views/Mangas/Edit.cshtml
@model MyMangaLibrary.Models.Manga

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>
    @Html.DisplayFor(model => model.Name)
</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ChapterCount" class="control-label"></label>
                <input asp-for="ChapterCount" class="form-control" />
                <span asp-validation-for="ChapterCount" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Summary" class="form-label mt-4"></label>
                <textarea class="form-control" asp-for="Summary" id="exampleTextarea" rows="3"></textarea>
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary btn-sm" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyMangaLibrary/Views/Mangas/Index.cshtml
@model IEnumerable<MyMangaLibrary.Models.Manga>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class="btn btn-primary btn-sm" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Chapter Count
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @using (Html.BeginForm("DecreaseChapter", "Mangas", new {id = item.ID}))
                {
                    <input class="btn btn-chap btn-sm" type="submit" title="-" value="-" />
                }
                @Html.DisplayFor(modelItem => item.ChapterCount)
                @using (Html.BeginForm("IncreaseChapter", "Mangas", new {id = item.ID}))
                {
                    <input class="btn btn-chap btn-sm" type="submit" title="+" value="+" />
                }
            </td>
            <td>
                <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.ID">Edit</a> 
                <a class="btn btn-info btn-sm" asp-action="Details" asp-route-id="@item.ID">Details</a> 
                <a class="btn btn-danger btn-sm"asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MyMangaLibrary/Views/Mangas/ShowSearchForm.cshtml
<h1>Search</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>